### ISSUE TITLE
Npc fuera de zona

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#1]
Hay npc nivel 85 en zonas nivel 30-35 cabo de tuerse espina hay demaciados y no tendrían que estar hay

![WoWScrnShot_112521_183133](https://user-images.githubusercontent.com/95107851/143660466-3dd245c2-66f0-4334-8caf-4611146a28bf.jpg)
![WoWScrnShot_112521_183550](https://user-images.githubusercontent.com/95107851/143660467-8c595d2a-39fa-4c44-acd3-9b464527567b.jpg)
![WoWScrnShot_112521_184228](https://user-images.githubusercontent.com/95107851/143660468-e6ea961c-1d31-4bda-9971-f460c1fa8359.jpg)

**Comment by ClownedDev** [comment]
Fix en el level de las creaturas Jungle Serpent.
