### ISSUE TITLE
Embate con escudo bug

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#10]
El embate con escudo del war prote está altísimo de daño mando captura de la prueba y consta que solo tenía set sañoso sin gemas ni nada  en el vídeo el tiene armadura pve 378 está imagen
Es lo que saque
![20211129_193114](https://user-images.githubusercontent.com/95107851/143974385-d6f9ee7a-fcd5-4000-89eb-b28d98da09e0.jpg)

Y esto es lo que se debe sacar el saca 5k con embate

https://user-images.githubusercontent.com/95107851/143974574-753386a6-dac7-4097-9500-81bdb8aa9602.mp4

**Comment by Klerigo** [comment]
Es el golpe final cuando se quitan los escudos rojos de los lados

**Comment by ClownedDev** [comment]
Fix embate de escudo con el warr ya saca un daño mas acorde y no sobre exagerado.
