### ISSUE TITLE
Bus de golpe pirulento dk profano

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#12]
El dk profano naturalmemte al golpear un objetivo con golpe pirulento las runas gastadas 1 escarcha 1 sangre. Deberian de convertirse wn runas de la muerte con un pequeño periodo de carga para utilizarlas 

https://user-images.githubusercontent.com/95107851/143992254-b805a750-9e6f-451b-8612-254530a35e85.mp4

**Comment by ClownedDev** [comment]
Fix golpe pirulento, ahora ya genera de forma correcta las runas de muerte.
