### ISSUE TITLE
ERROR - DISIPAR MAGIA 

### ISSUE THREAD

**Issue by jhorman159** [ClownedDev/WoWGerrero#13]
Memememomun
Hechizo Sacerdote: Disipar Magia / Spell ID = 65546
El hechizo debería cumplir la función en un personaje aliado, ya sea grupo/banda, en la foto se puede apreciar que el objetivo no es válido, cuando simplemente debería activarse el hechizo.
![ERROR-1](https://user-images.githubusercontent.com/95391795/144342952-342de798-8e44-49a1-8832-d8726fe262a0.png)
https://es.wowhead.com/spell=65546/disipar-magia

**Comment by ClownedDev** [comment]
Fix las mecánica de disipar magia, ahora ya limpia a aliados y entra en combate al intentar limpiar a enemigos de forma normal.
