### ISSUE TITLE
FRAGMENTOS DE ESPIRITU

### ISSUE THREAD

**Issue by jhorman159** [ClownedDev/WoWGerrero#14]
Memememomun
Fin de los días
Las mazmorras HC, están dando fragmentos de espiritu, actualmente el nivel de equipo de los jugadores no da para ir más allá de Fin de los días, el reporte es para informar que no está dando fragmentos de espiritus el boss final de la mazmorra, el cual por su dificultad con este set, debería dar antes una mayor recompensa
![ERROR-2](https://user-images.githubusercontent.com/95391795/144346682-5eb2850d-a596-42d1-8076-c36d671dd6f4.png)
.

**Comment by ClownedDev** [comment]
Son items agregados al modo blizzlike por ende no están pensados para los jefes finales, no están mal están como los acomodamos para que no sea tan fácil el farmeo de los mismos pero tampoco tan difícil.
