### ISSUE TITLE
Maestro jinete

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#17]
El maestro  de vuelo no muestra las rutas de vuelo  que esta en  marjal revolcafango que esta en esta en piñón de barro sola mente muestra una ruta de vuelo nada mas y no puedo entregar la misión  [A la Cima]
![Sin_titulo_8](https://user-images.githubusercontent.com/95107851/145248060-e5d04c50-bb6c-4479-888a-317fa2538fcb.png)
![Sin_titulo-2](https://user-images.githubusercontent.com/95107851/145248064-176577e9-b297-439e-a83d-bf206db6e8d8.png)

**Comment by ClownedDev** [comment]
Fixeado ahora ya muestra todas las rutas de forma correcta
