### ISSUE TITLE
Misión la puerta murketh

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#19]
Al momento de cojer la misión al lado hay un npc el cual tu hablas con el y el te manda con un pajaro a los parrales el cual debes destruir con el ítem  que le da la misión y al momento de hablar con él npc no te manda para ningún lado y no se puede completar la misión sin hablar primero con el npc       ID=10129
Así debería funcionar

https://youtu.be/M4R09m5SwF8

**Comment by ClownedDev** [comment]
Trabaja sin problemas tras intentarlo 2 veces.
