### ISSUE TITLE
Tabernero defectuoso

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#2]
El tabernero del distrito de los enanos en ventormenta no da la opción de hacer piedra hogar, al interactuar con el automáticamente haber como vendedor la id del npc es  44235
![WoWScrnShot_112621_140459](https://user-images.githubusercontent.com/95107851/143660682-4ce8b042-a18b-46a1-87fd-a3b3049ff7fa.jpg)

**Comment by ClownedDev** [comment]
Fix Thaegra Labrapiedra ya te muestra su menú para colocar tu hogar.
