### ISSUE TITLE
Misión por todos los ciervos!

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#21]
La misión a por todos los ciervos está bug porque los ciervos lo siguen hasta cierto punto de hay como que ellos toparan con una muralla invisible porque no puede pasar de hay....ID=25392

![unknown-2](https://user-images.githubusercontent.com/95107851/145435153-ef2d08f3-17d8-46af-83a9-590eb939cdb0.png)

Así debería de funcionar

https://youtu.be/Koi79_tbv9U

**Comment by ClownedDev** [comment]
Fix ahora se completa sin problemas.
