### ISSUE TITLE
Cadena de misión bug

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#22]
La misión de activa u empiezan a salir oleadas del portal como aparece en el vídeo, y aparecen aliados también, y en el server solo salen 6 elementales y cuando matas a 1 salen 3 más, y aliados solo aparecen 1 cada 3 oleadas esa es la primera fase y luego la segunda fase hay que entrar al portal, pero si la primera no jala la segunda menos

Así debería de funcionar

https://youtu.be/CB8INqH4qhM

**Comment by ClownedDev** [comment]
No veo ninguna falla tras intentarlo varias veces.
