### ISSUE TITLE
Lycanthoth el corrupto

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#23]
En esta misión cuando invocas al lobo negro y lo matas tendría que aparecer un lobo blanco que te lleva en su lomo pero acá cuando mato al lobo negro no sale el blanco y no se puede completar la misión
ID =  25272

https://user-images.githubusercontent.com/95107851/145700229-dedf9f95-956d-4279-b346-f863bb340cc6.mp4

Así debería funcionar

https://youtu.be/C-UdETGa6Lg

**Comment by ClownedDev** [comment]
Fix ahora ya llama al lobo blanco al morir tras intentar.
