### ISSUE TITLE
Misión a vuelo de pájaro

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#25]
se usa el item para tranformarce en un ave como dice hay y volar hasta cierto punto una vez hecho eso vuelve todo es automatico solo consiste en trasformarse volar y volver nada mas pero al usar el item no pasa nada  ID de misión =9718.     ID de item de Mision=25465

![unknown-4](https://user-images.githubusercontent.com/95107851/145739957-12c1fb30-ea4a-4381-8a19-d1055e6dded8.png)

Así debería funcionar
https://youtu.be/zcqG-dsbJlg

**Comment by ClownedDev** [comment]
Fix tras intentar, ahora ya te cambia de forma y te la quita al terminar la ruta de vuelo.
