### ISSUE TITLE
Fallos con "Las Granjas Grito de Guerra"

### ISSUE THREAD

**Issue by Candreloss** [ClownedDev/WoWGerrero#26]
La mision en circunstancias normales debe completarse al llegar a una zona determinada tras haber completado el primer objetivo, tal como pude probar no funciona. Sin mas que agregar esperare sea solucionado, buenas noches.

**Comment by ClownedDev** [comment]
La misión se completa sin problemas tras intentarlo no se ve ninguna falla.
