### ISSUE TITLE
Talento de trueno ensordecedor

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#27]
Ese talento lo que hace es que cuando el chaman tiene activado el escudo de relámpagos tiene un 60% de que cuando inflija daño con cadena de relámpagos o descarga de relámpagos recupere 2% de mana y te de una carga de de escudo de relámpagos.

El bug está en qué al hacer daño sobre da la carga de escudo se relámpagos pero el 2% que debería debería de dar casi no sale 

![20211212_191709](https://user-images.githubusercontent.com/95107851/145821607-5c425be2-1228-4e4f-9284-6731000f81d0.jpg)

**Comment by Klerigo** [comment]
Es casi nulo el mana que da osea no sale o sale muy pocas veces

**Comment by ClownedDev** [comment]
Fix tras intentar, ahora ya salta en mayor % su efecto de forma correcta.
