### ISSUE TITLE
Npc en entrada de mazmorra

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#29]
Este npc lvl 83 de id 45523 sale en la mazmorra STRATHOLME que es de lvl 48-51  y ataca a y mata a todo jugador que entre

![WoWScrnShot_121421_205659](https://user-images.githubusercontent.com/95107851/146304105-696fa724-26c1-44a9-86f1-384b68edd37f.jpg)

**Comment by ClownedDev** [comment]
Se corrigió la posición y la zona de esa creatura.
