### ISSUE TITLE
Misión El milagro de aessina

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#31]
El npc que nos tendría que completar la misión está bug al interactuar con el solo sale un diálogo normal en ves de completarnos la misión y poder seguir con la cadena ID de misión 25372,.       ID del npc 52838
![16399513938057249939033009616167](https://user-images.githubusercontent.com/95107851/146692385-ae4d6b28-3666-4ab6-bb49-5cae35a1beb0.jpg)

Así debería funcionar
https://youtu.be/uScIX8KPaTw

**Comment by ClownedDev** [comment]
Se fixeo el gossip del npc de forma correcta.
