### ISSUE TITLE
Npc bug o spell bug

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#32]
Bug de lanza salvavidas en tierras altas crespusculares practicamente esta bien elevado el daño adjunto las siguentes fotos con el dps y todo  la id de la spells: 92733 y la id del npc es 49680

![unknown-6](https://user-images.githubusercontent.com/95107851/147420838-cb234cd3-8a82-4bfe-8013-e8c4b90b9a38.png)
![unknown-7](https://user-images.githubusercontent.com/95107851/147420839-062539a4-502a-4764-9767-36c4d84921c0.png)
![unknown-8](https://user-images.githubusercontent.com/95107851/147420840-36e9bc07-76f2-43f2-acd1-7126e0c82fe5.png)

**Comment by ClownedDev** [comment]
Fixeado, se podrá ver en el siguiente reinicio.
