### ISSUE TITLE
Cadenas de misones de Invasion de las tierras del fuego

### ISSUE THREAD

**Issue by anacleyta** [ClownedDev/WoWGerrero#33]
[Un ritual de llamas] falta un add para terminar la mision y falta el npc para completarlas 
![WoWScrnShot_110821_112243](https://user-images.githubusercontent.com/93929625/147494532-38419e78-d661-4472-a01e-68d1b3c8ff99.jpg)

imagende como tendria que ser 
link de wow head https://es.wowhead.com/quest=29195/un-ritual-de-llamas

**Comment by anacleyta** [comment]
Alas ardiente , no toma la zona del portal para invocar al fenix
![WoWScrnShot_112921_133443](https://user-images.githubusercontent.com/93929625/147494903-b128985d-d453-427c-8f3b-dfe134a3c226.jpg)
https://es.wowhead.com/quest=29148/alas-ardientes

**Comment by anacleyta** [comment]
misones los procteros de hyjal y aliviando el dolor no cambia la zona por ende no aparecen los add que hay que matar 
![WoWScrnShot_112921_142007](https://user-images.githubusercontent.com/93929625/147495201-4c782c1a-d299-4b9f-ae50-089346a85898.jpg)
![WoWScrnShot_112921_142111](https://user-images.githubusercontent.com/93929625/147495320-7839d552-76b0-4374-863e-c4521351d963.jpg)
https://es.wowhead.com/quest=29128/los-protectores-de-hyjal
https://es.wowhead.com/quest=29246/aliviando-el-dolor

**Comment by anacleyta** [comment]
la Bendicion de la naturaleza ,mismo problema del portal no toma la zona por ende no es posible invokar a la araña
![WoWScrnShot_113021_144108](https://user-images.githubusercontent.com/93929625/147495704-2e677641-9d57-4249-8fbb-a8c42c77fd07.jpg)
https://es.wowhead.com/quest=29162/la-bendici%C3%B3n-de-la-naturaleza

**Comment by anacleyta** [comment]
Liberando la presion al no cambiar la zona los cual tiene que haber adds de lvl 85 no dropean las escamas
![WoWScrnShot_113021_150055](https://user-images.githubusercontent.com/93929625/147496378-a14966a6-5154-477d-9585-a0646c6cadc8.jpg)
![WoWScrnShot_113021_151205](https://user-images.githubusercontent.com/93929625/147496384-ff6de352-f659-431f-b22c-1e5d2157c5b0.jpg)
https://es.wowhead.com/quest=29248/liberando-la-presi%C3%B3n

**Comment by ClownedDev** [comment]
Se recreo todas las phases y smarths de hyjal requiere mayor atencion y reportes actuales con fotos actuales tambien.
