### ISSUE TITLE
Loot de Beth'tilac

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#34]
Al matar al boss de FL "Beth'tilac" su loot queda arriba en la telaraña por lo tanto no pueden lotear
![WoWScrnShot_122721_204631](https://user-images.githubusercontent.com/95107851/147522790-13cbb950-b51f-4b4c-9055-7aa3ea03c8e4.jpg)
![WoWScrnShot_122721_204822](https://user-images.githubusercontent.com/95107851/147522797-02d615d9-2038-41ae-b6da-7faaf8597cea.jpg)

**Comment by ClownedDev** [comment]
Fix problemas con el movement de este boss.
