### ISSUE TITLE
2do teleport bug de pozo de la eternidad

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#35]
Despues de matar al eco de sylvanas debes usar el teleport para ir al siguiente boss, dicho teleport solo debe mostrarte el siguiente boss pero te muestra todos y debes ir al primero de nuevo
![WoWScrnShot_122821_214546-1](https://user-images.githubusercontent.com/95107851/147625809-3924e203-bfac-4dc0-9e1e-aace46fd059e.jpg)
![WoWScrnShot_122821_214558-1](https://user-images.githubusercontent.com/95107851/147625815-63a75a2a-8486-4b6d-a81a-8bb0bc003903.jpg)

Debería de ser como el primero:

![WoWScrnShot_122821_214619](https://user-images.githubusercontent.com/95107851/147625827-b2ba7199-ad28-4ca1-a8dc-8fc597168fab.jpg)

**Comment by ClownedDev** [comment]
fixeado en su totalidad.
