### ISSUE TITLE
Mision bug.

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#36]
Misión ..ahora sí la as liado kul.....ID 14096

Lo que pasa es que aunque ya tengas la llave para abrir la jaula, le das clic a la jaula sale la barra de casteo pero al completarse dice NO CONSEGUIDO

![WoWScrnShot_122821_215504](https://user-images.githubusercontent.com/95107851/147626266-640cc6ee-cd27-46ea-b5e1-09ae01cefae5.jpg)
![WoWScrnShot_122821_215457](https://user-images.githubusercontent.com/95107851/147626269-e9d052f6-e223-4b77-beae-fc210e4bd4b2.jpg)
![WoWScrnShot_122821_215453](https://user-images.githubusercontent.com/95107851/147626270-8bd6ccad-e26e-4a1e-811a-b9df0784bfad.jpg)
![WoWScrnShot_122821_215446](https://user-images.githubusercontent.com/95107851/147626272-1b6fe160-13f6-4273-b58a-447c531987a1.jpg)

Así debería funcionar
https://youtu.be/7IOLkT5954s

**Comment by ClownedDev** [comment]
Fixeado a modo blizzlike
