### ISSUE TITLE
Boss bug

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#37]
boss bug  mazmorra pináculo de utgarde no se puede atacar ni me ataca ,voliv a intentar matarlo pero otra vez se bugeo no puedo hacerle dps

![unknown-9](https://user-images.githubusercontent.com/95107851/147626481-8796a86a-60d0-4d24-9c9b-d6b46543f2a5.png)
![unknown-10](https://user-images.githubusercontent.com/95107851/147626490-ea0b5c03-f214-48b6-a6ed-8a6d28c0664d.png)

**Comment by ClownedDev** [comment]
Fixeado.
