### ISSUE TITLE
Mision: discurso de graduación

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#38]
Cuánto subes al dar el discurso no están los npc que deberían escuchar el discurso por ende no se puede completar la mision ID de misión 25315

![WoWScrnShot_122821_232733](https://user-images.githubusercontent.com/95107851/147684493-d9bac543-9a7d-404b-809e-ac0376a1499c.jpg)
![WoWScrnShot_122821_232743](https://user-images.githubusercontent.com/95107851/147684499-893dcf2a-8508-4bc5-8e98-87f40e52fd28.jpg)

Cómo debería ser:
https://youtu.be/YDHJlF8HxsU

**Comment by ClownedDev** [comment]
fix
