### ISSUE TITLE
Npc duplicados 

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#39]
Por todo hijal se encuentran npc duplicados aquí unas muestras
![WoWScrnShot_122821_232428](https://user-images.githubusercontent.com/95107851/147684769-86ce4ca4-bc8e-4493-8dd5-ec0e3b534a7e.jpg)
![WoWScrnShot_122821_230757](https://user-images.githubusercontent.com/95107851/147684770-92dfad2f-64e4-42ff-b263-5832444d81d7.jpg)
![WoWScrnShot_122821_231121](https://user-images.githubusercontent.com/95107851/147684771-0466fcfc-a733-44f5-9f0c-381c8efd18fa.jpg)
![WoWScrnShot_122821_232113](https://user-images.githubusercontent.com/95107851/147684772-da4c1466-ddd7-4137-b29e-575986714e3a.jpg)
![WoWScrnShot_122821_232134](https://user-images.githubusercontent.com/95107851/147684773-6908e8d9-55b6-419f-8f40-024918ec16d2.jpg)
![WoWScrnShot_122821_232145](https://user-images.githubusercontent.com/95107851/147684774-61c78812-0596-4472-a3cf-ca285a203b07.jpg)
![WoWScrnShot_122821_232743](https://user-images.githubusercontent.com/95107851/147684776-197c1631-b897-45ff-98c4-dadc76a65938.jpg)

**Comment by ClownedDev** [comment]
creaturas duplicadas eliminadas.
