### ISSUE TITLE
Spell escudo de vengador

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#4]
El problema es que se a testeado el escudo vengador y anda bajo de dps porque cuando el usuario usa todos sus cds aún así es poco lo que saca la id 31935 

Lo testie con un paladin full Impala y con gemas 
Contra un cazador sañoso sin nada solo la armadura
La diferencia es abismal y solo le saco 6k a otro Impala le equivale a 3 o 4 k full cds contra un sañaso le saco 10k usando todo lo que tiene el paladin .

**Comment by ClownedDev** [comment]
Habilidad en correcto funcionamiento, no requiere ningún fixeo su daño base es de 3655k de daño y en críticos máximos de 6k exageradamente 7k según el oficial.

Datos extraídos de video con paladín prot del servidor oficial en el 4.3.4: https://www.youtube.com/watch?v=KdjK4fuD0ow Año 2012.
