### ISSUE TITLE
Npc inmortal

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#40]
Npc inmortal en minas de la muerte 
![unknown-18](https://user-images.githubusercontent.com/95107851/147827368-a8f1ffc0-427a-4b0b-9309-0a8d325eb679.png)
![unknown-11](https://user-images.githubusercontent.com/95107851/147827382-fdc5ecf3-22d4-4361-a2f7-b352b7d95d07.png)

**Comment by ClownedDev** [comment]
Los bots estarán desactivados de mazmorras por un tiempo hasta fixearlos un poco mejor, se requiere que se verifique este npc con pjs normales.
