### ISSUE TITLE
Invasiones a las tierras del fuego

### ISSUE THREAD

**Issue by anacleyta** [ClownedDev/WoWGerrero#41]
[El santuario no debe caer] la mecanica no funciona aparecen los add pero malfurion no comienza en ritual y nunca se termina la mision 
![WoWScrnShot_010322_130500](https://user-images.githubusercontent.com/93929625/147952716-3aaffba6-87de-4f53-ba37-3b9761e91527.jpg)
![WoWScrnShot_010322_130507](https://user-images.githubusercontent.com/93929625/147952722-53a0c11c-66dc-47e2-b1d6-4ef48fa06fcc.jpg)
link de wow head https://es.wowhead.com/quest=29198/el-santuario-no-debe-caer

**Comment by ClownedDev** [comment]
requiere mayor test
