### ISSUE TITLE
Npc faltante

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#43]
buenas vengo a reportar la mision de Reforja la espada quel´Dalar 
![unknown-22](https://user-images.githubusercontent.com/95107851/148632396-43e87dd2-ea6d-4599-8140-f5b9c5d2094f.png)
los npc sale que estan en esa ubicacion pero deverian de estar aqui
![unknown-21](https://user-images.githubusercontent.com/95107851/148632408-0dae99ec-13e9-4037-91d7-6bb2491c515e.png)

Así debería de ser

https://es.wowhead.com/quest=24461/reforjar-la-espada

**Comment by ClownedDev** [comment]
Fix
