### ISSUE TITLE
Bug de portal 

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#44]
buenas que pera reportan bug con el portal a tierras devastadas de orgimmar que no deja q los players lvl 57 cojan el portal
![WoWScrnShot_010722_231453](https://user-images.githubusercontent.com/95107851/148632525-df0c9881-0563-4fa9-bd1f-f66e70903304.jpg)

**Comment by ClownedDev** [comment]
Fix Portal a Las Tierras Devastadas.
