### ISSUE TITLE
Bug de encantar manos

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#46]
Cuando encantas los guantes o capa con cualquier hechizo al querer aplicar muelle de sinapsis por ejemplo a los guantes se debe remplazar por el encantamiento anterior pero aquí se mantienen las 2 cosas el muelle que se agrega al guante mediante ingeniería y se queda también el encantamiento lo mismo debería pasar con la capa

**Comment by ClownedDev** [comment]
Mas información sobre este reporte ya que no se puede reproducir, video de preferencia.
