### ISSUE TITLE
Bugs de pozo de la eternidad

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#49]
1. andar en las sombras dura 1 seg y deberia durar 1 segundo por carga
2. los ojos no se mueven

Así debería funcionar

https://youtu.be/JkPNrodYozs

**Comment by ClownedDev** [comment]
Verificado, todo funciona muy bien en nuestro servidor. Caso contrario por favor dejar un video con imágenes para ver que no trabaja como es debido, hasta donde se verifico todo va bien.
