### ISSUE TITLE
Profecion faltante en Npc

### ISSUE THREAD

**Issue by Klerigo** [ClownedDev/WoWGerrero#5]
Falta la profecion de sastrería en el nuevo npc 
![WoWScrnShot_112721_130510](https://user-images.githubusercontent.com/95107851/143695969-79835f20-7ad3-4413-a722-66b5d7dda62c.jpg)
![WoWScrnShot_112721_130506](https://user-images.githubusercontent.com/95107851/143695983-46328520-1e53-475b-86ac-bf3dea1cffc6.jpg)

**Comment by ClownedDev** [comment]
La profesión si esta, no te es visible por que ya la tienes aprendida. Eliminala de tu pj y habla nuevamente con el npc para que su menú te sea visible.

Pdt: el npc no te muestra lo que ya tienes.
