### ISSUE TITLE
Invacion a las tierras del fuego

### ISSUE THREAD

**Issue by anacleyta** [ClownedDev/WoWGerrero#51]
Mision leyara  , falla al entregar la mision malfurion desaparece y no te dan mas misiones para seguir asiendo las restante no esta en donde subire la foto ni afuera del portal a las tierras del fuego ni adentro desaparece del mapa 
![WoWScrnShot_011122_204753](https://user-images.githubusercontent.com/93929625/149039503-c2090122-67e3-4b29-86d9-d9701d13bf6d.jpg)
![WoWScrnShot_011122_204824](https://user-images.githubusercontent.com/93929625/149039525-8934ec36-beb6-4552-96ea-fc9f22cfaf16.jpg)
link de wow head https://es.wowhead.com/quest=29200/leyara

**Comment by ClownedDev** [comment]
Se puede completar tras intentarlo varias veces sin problemas.
