### ISSUE TITLE
Bug - Error en la ultima Mision Estepas Ardientes

### ISSUE THREAD

**Issue by JoSeDanniiel** [ClownedDev/WoWGerrero#54]
Nombre PJ: Dabu
Mision
En la ultima parte de las msiones de la zona de las ESTEPAS ARDIENTES para completar y obtener el logro de misiones no se puede completar dado que la ultima mision no aparece .. el PNC "Eitrigg" mostro que tenia una mision y despues de unos minutos se desaparecio el simbolo de mision
![Evidencia](https://user-images.githubusercontent.com/98504390/151285517-fae67cb1-9927-4177-8fd7-09cc69e5d1c4.jpg)

Link: https://es.wowhead.com/npc=48569/eitrigg

**Comment by ClownedDev** [comment]
Necesito mas detalles, que mision tendria que darte. Link de la mision faltante.

**Comment by JoSeDanniiel** [comment]
Ps de mi parte inicie las misiones normalmente y segui el registro de
logros pero como miro en la imagen que faltando 1 mision para obtener el
logro entonces
y la ultima mision que me dio fue esta:
https://es.wowhead.com/quest=28456/botín-de-guerra que ni siquiera fue
necesario hacerla dado que se autocompleto y de ahi no se que hacer para
obtener el logro.. esto lo hago porque me gusta el proceso de misiones de
todo el juego y asi como le dije al GM brand estoy aqui para testear
misiones y ver que todo funcione de manera correcta
