### ISSUE TITLE
Abalorio "artefacto de khaz goroth" no funciona

### ISSUE THREAD

**Issue by Plinshi** [ClownedDev/WoWGerrero#57]
Galehna
Objeto - Abalorio: artefacto de khaz goroth 

Este objeto al consumir las 5 cargas que otorga, deberia dar un buff de 2540 en el atributo de maestria, celeridad, o critico (dependiendo de cual sea el mayor). Actualemente en el servidor solamente consume las cargas, pero no otorga ningun buff.

**Comment by ClownedDev** [comment]
Fix tras intentar.
