### ISSUE TITLE
Artefacto de khaz goroth

### ISSUE THREAD

**Issue by Plinshi** [ClownedDev/WoWGerrero#58]
Abalorio
Galehna

Visto en el discord que el artefacto habia sido arreglado me fui directo a los dummys para probarlo.
Resultado: Al conseguir las 5 cargas del abalorio, al usarlo para obtener el buff de 2450 puntos, sigue ocurriendo que las marcas se consumen, el abalorio agarra CD de 2 minutos, pero sige sin otorgar dicho buff.

**Comment by ClownedDev** [comment]
El item esta trabajando de forma muy normal, verificado nuevamente. Si desea mayor informacion puede revisar el siguiente link y las clases que pueden obtener el beneficio en modo BlizzLike.
https://es.wowhead.com/item=69113/artefacto-de-khazgoroth
![Sin título](https://user-images.githubusercontent.com/29180800/152459676-8c06418a-9b0f-48da-b3d5-bb7ed616b73d.png)
