### ISSUE TITLE
Guante de ingeniería

### ISSUE THREAD

**Issue by Elvless** [ClownedDev/WoWGerrero#6]
El inyector de sanación espinal (un componer de ingeniería) es una spell que se añade a los guantes que cura cierta cantidad de vida y tiene cd de 1 minuto, funciona todo correctamente salvó al entrar a bg, en bg se usa una vez y no se puede volver a usar hasta salir de la bg o relogear

**Comment by ClownedDev** [comment]
Fix ahora ya muestra el tiempo de espera para reusar la habilidad.
