### ISSUE TITLE
Legado de Leyara

### ISSUE THREAD

**Issue by anacleyta** [ClownedDev/WoWGerrero#65]
Ya Malfurion da la mision y funciona correctamente el logro te lo da y la mision se completa normalmente pero al darte el  [Guardapelo manchado de humo] te llega por correo y no funciona el item tiene que darte la mision pero no funciona y no te da nada aparece como un objeto de mision pero tampoco te da ninguna mision aca dejo foto , al venir donde hay que completarla tampoco el npc empieza ni termina la mision 
![WoWScrnShot_021322_105433](https://user-images.githubusercontent.com/93929625/153756807-3eeec73e-59dc-4360-94a6-2792f1b1cadb.jpg)
![WoWScrnShot_021322_112314](https://user-images.githubusercontent.com/93929625/153757551-353be761-52ea-4e52-990c-7ba26dbe3721.jpg)
https://es.wowhead.com/quest=29298/un-guardapelo-manchado-de-humo

**Comment by ClownedDev** [comment]
Esta trabajando sin problemas tras intentarlo 2 veces.
