### ISSUE TITLE
Subida de cura en palabra de gloria de mas

### ISSUE THREAD

**Issue by Seven7113** [ClownedDev/WoWGerrero#66]
Silver
Seleccionar uno de los siguientes: Hechizos
Descripción del fallo lo mas detallado posible y como tendría que trabajar de forma correcta
Imagen para detallar aun mas.  : Fixeo de palabra de gloria ahora cura mas de lo debido de pasar de curar maximo 12k en critico ahora tiene de promedio  maximo 141k 
Coloco screen de maxima de cura y promedio de cura que tiene la palabra de gloria ahora ( borde inferior derecho)
Video para detallar aun mas un correcto funcionamiento o una posible falla

![WoWScrnShot_030122_195133](https://user-images.githubusercontent.com/100738143/156274832-7fafa051-301d-4943-be7f-789a2cf17485.jpg)
.

**Comment by ClownedDev** [comment]
Fix
