### ISSUE TITLE
Revision en texturas bola en Zon H

### ISSUE THREAD

**Issue by Seven7113** [ClownedDev/WoWGerrero#67]
La textura de la bola en la mecanica zon os manda a lugares ramdon en la fase. 
Por mas que uno mira directo al boss toma a veces direccion distinta
https://drive.google.com/file/d/1Xvsy0JGGhNVRXczXj9BIx1iIzW6ezfN3/view?usp=sharing
https://drive.google.com/file/d/13ktUMnQ2IUbsQ8sdVrH3ni4HbGSUF6I6/view?usp=sharing

**Comment by ClownedDev** [comment]
No se puede reproducir el bug, la esfera sale de forma normal tras intentarlo de forma correcta.
