### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by anacleyta** [ClownedDev/WoWGerrero#69]
![WoWScrnShot_030422_145221](https://user-images.githubusercontent.com/93929625/156817234-552531a6-78e2-4bbf-bec8-2949799b41f2.jpg)
podrian revisar los 2 siguieten items   [Dragonira, el Reposo de Tarecgosa] y  [Naipe de la Luna Negra: Volcán] ya que tarda mucho tiempo en activarse y otro no se acitva casi nunca aca dejo fotos de 2 recount de 34 y 35 golpes en el cual tardo ese tiempo en activarse 1 sola ves es baston y el naime en ninguno de los dos se activo tanto como su buff como su daño 
![WoWScrnShot_030422_145340](https://user-images.githubusercontent.com/93929625/156816789-78543f28-fdac-4a07-b62e-5fb1211b25f1.jpg)

![WoWScrnShot_030422_144736](https://user-images.githubusercontent.com/93929625/156816755-054354bf-dfce-42cf-9406-c86d2b5012c4.jpg)
![WoWScrnShot_030422_145223](https://user-images.githubusercontent.com/93929625/156816785-59667db6-e3ae-4dda-8c28-02ea1f97db4a.jpg)

**Comment by ClownedDev** [comment]
fix
