### ISSUE TITLE
Bug en Fin de los dias

### ISSUE THREAD

**Issue by Elvless** [ClownedDev/WoWGerrero#7]
En la diaria heroica (Fin de los días) el boss Eco de jaina pega demasiado con su cast básico que es una bola de fuego, pega 80k y más incluso a un tank con cada cast,a los dps les oneshoteaba a algunos, es imposible hacerlo incluso entre 5 nos mató demasiado rápido, corregir su daño porfavor

**Comment by ClownedDev** [comment]
Fix Piroexplosión daño corregido de 95k a su daño normal entre 30 a 32k de forma correcta.
