### ISSUE TITLE
misiones

### ISSUE THREAD

**Issue by anacleyta** [ClownedDev/WoWGerrero#72]
el ncp de la siguiente foto no deja tomar la mision y en la zona ya no te dan mas misiones de seguro es algun npc que da una seguidillas de misiones o habilitan las demas ya que no hay ninguna mision mas para tomar en todo el mapa y segun el logro hay mas de 25 la sona es pantano de las penas 
![WoWScrnShot_031122_222737](https://user-images.githubusercontent.com/93929625/158029494-563bb4ac-b78b-417a-9973-9b297dee0a04.jpg)
![WoWScrnShot_031122_222819](https://user-images.githubusercontent.com/93929625/158029498-97700614-8684-4425-8122-bb235e57ac94.jpg)
![WoWScrnShot_031222_150815](https://user-images.githubusercontent.com/93929625/158029562-a481ac32-6c2b-49cd-812c-aa8aa8f6ea07.jpg)
https://es.classic.wowhead.com/npc=5391/galen-bonguarda

**Comment by ClownedDev** [comment]
fix
